/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface EgDarkmodeToggle {
        "active": boolean;
        "iconOnly": boolean;
        "label": string;
    }
}
declare global {
    interface HTMLEgDarkmodeToggleElement extends Components.EgDarkmodeToggle, HTMLStencilElement {
    }
    var HTMLEgDarkmodeToggleElement: {
        prototype: HTMLEgDarkmodeToggleElement;
        new (): HTMLEgDarkmodeToggleElement;
    };
    interface HTMLElementTagNameMap {
        "eg-darkmode-toggle": HTMLEgDarkmodeToggleElement;
    }
}
declare namespace LocalJSX {
    interface EgDarkmodeToggle {
        "active"?: boolean;
        "iconOnly"?: boolean;
        "label"?: string;
    }
    interface IntrinsicElements {
        "eg-darkmode-toggle": EgDarkmodeToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "eg-darkmode-toggle": LocalJSX.EgDarkmodeToggle & JSXBase.HTMLAttributes<HTMLEgDarkmodeToggleElement>;
        }
    }
}
